# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: 
      - develop
      - release/*
      - SPIKE
      - feature/github-actions
    tags: v*

  pull_request:
    branches: 
      - develop
      - release/*
      - SPIKE
      - feature/github-actions

env:
  AWS_EC2_METADATA_DISABLED: true
  GITHUB_ACTIONS_PULL_REQUEST: ${{ github.event.pull_request.number }}
  DEPLOY_SOURCE_DIR: site/build/libs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Get Tag Version
      run: echo "GITHUB_ACTIONS_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clone Github Actions S3 Deploy
      run: git clone https://github.com/perfectsense/github-actions-s3-deploy.git
    - name: Build with Gradle
      run: ./github-actions-s3-deploy/build-gradle.sh
    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        DEPLOY_BUCKET: ${{ secrets.DEPLOY_BUCKET }}
      run: ./github-actions-s3-deploy/deploy.sh
